# Document: https://docs.travis-ci.com/user/deployment
# Document Heroku: https://devcenter.heroku.com/articles/build-docker-images-heroku-yml

sudo: required
language: node_js
cache:
  directories:
    - node_modules

notifications:
  email:
    on_failure: change

node_js:
  - '13'

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.16.1

before_install:
  # import heroku CLI
  # add heroku auth:token to TravisCI Environment Variables (https://travis-ci.org/github/thuydx98/human-resource-management/settings)
  - echo 'PATH="/usr/local/heroku/bin:$PATH"' >> ~/.profile
  - sudo apt-get update
  - sudo apt-get install python3

script:
  - docker build -f Dockerfile -t hcmus-movie .
  - docker images

after_success:
  - heroku container:login
  - docker tag hcmus-movie registry.heroku.com/hcmus-movie/web
  - docker push registry.heroku.com/hcmus-movie/web
  - heroku container:release web --app hcmus-movie
